title:              olenmg's blog
email:              o.olenmg@gmail.com
description:        Development & Studying
author:             olenmg
baseurl:            "/"
url:                "https://olenmg.github.io"

# Social Profiles
twitter_username:   
github_username:    olenmg
facebook_username:  
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jemoji
